-- 코드를 작성해주세요
SELECT TH.ID AS ID
FROM ECOLI_DATA TH
RIGHT JOIN (
    SELECT SE.ID AS ID
    FROM ECOLI_DATA SE
    RIGHT JOIN ECOLI_DATA FI
    ON SE.PARENT_ID = FI.ID
    WHERE FI.PARENT_ID IS NULL
) AS SEE
ON TH.PARENT_ID = SEE.ID
WHERE TH.PARENT_ID IS NOT NULL;