SELECT AA.HISTORY_ID, TRUNC((AA.FEE * (100 - NVL(CC.DISCOUNT_RATE, 0)))/100) AS FEE
  FROM (SELECT A.HISTORY_ID,
               B.CAR_TYPE,
               CASE WHEN (A.END_DATE - A.START_DATE + 1) >= 90 THEN '90일 이상'
                    WHEN (A.END_DATE - A.START_DATE + 1) >= 30 THEN '30일 이상'
                    WHEN (A.END_DATE - A.START_DATE + 1) >= 7 THEN '7일 이상'
                    ELSE '0일 이상'
                END AS DURATION_TYPE,
                (A.END_DATE - A.START_DATE + 1)*B.DAILY_FEE AS FEE
           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A, 
                CAR_RENTAL_COMPANY_CAR B
          WHERE A.CAR_ID = B.CAR_ID
            AND B.CAR_TYPE = '트럭') AA,
       CAR_RENTAL_COMPANY_DISCOUNT_PLAN CC
 WHERE AA.DURATION_TYPE = CC.DURATION_TYPE(+)
   AND AA.CAR_TYPE = CC.CAR_TYPE
 ORDER BY TRUNC(AA.FEE * (100 - NVL(CC.DISCOUNT_RATE, 0))/100) DESC, AA.HISTORY_ID DESC
 
