-- 코드를 입력하세요
SELECT B.HOUR, NVL(A.COUNT, 0)
  FROM (SELECT TO_NUMBER(SUBSTR(TO_CHAR(DATETIME, 'YYYYMMDDHH24MISS'), 9, 2)) AS HOUR, COUNT(*) AS COUNT
          FROM ANIMAL_OUTS
         GROUP BY SUBSTR(TO_CHAR(DATETIME, 'YYYYMMDDHH24MISS'), 9, 2)) A,
       (SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL <=24) B
 WHERE A.HOUR(+) = B.HOUR
 ORDER BY B.HOUR